### ISSUE TITLE
Installing relay-devtools on M1 mac fails while trying to download electron-v1.8.8-darwin-arm64.zip

### ISSUE THREAD

**Issue by Lalitha-Iyer** [relayjs/relay-devtools#137]
Repro:
`yarn add relay-devtools` 

Error:
```
Error: Failed to find Electron v1.8.8 for darwin-arm64 at https://github.com/electron/electron/releases/download/v1.8.8/electron-v1.8.8-darwin-arm64.zip
    at Request.<anonymous> (/Users/liyer/tvui/node_modules/nugget/index.js:169:61)
    at Request.emit (node:events:527:28)
    at Request.onRequestResponse (/Users/liyer/tvui/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (node:events:527:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:631:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:494:22)
    at TLSSocket.emit (node:events:527:28)
    ```

**Comment by Lalitha-Iyer** [comment]
May be this [PR](https://github.com/relayjs/relay-devtools/pull/112) would fix this ?

**Comment by voideanvalue** [comment]
Thanks. I'll test and get it merged.

**Comment by voideanvalue** [comment]
merged https://github.com/relayjs/relay-devtools/pull/135 and validated fix on m1 macbook

**Comment by andreassavva** [comment]
I have the same issue with 1.4.0
