### ISSUE TITLE
Failed to execute 'postMessage' on 'Window': Response object could not be cloned.

### ISSUE THREAD

**Issue by jaycenhorton** [relayjs/relay-devtools#20]
The following error is dumped into my console every few seconds (I'm assuming when I'm fetching some relay data) 
```
Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Response object could not be cloned.
    at Object.send (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/backendAgent.js:185:14)
    at Bridge._flushOutgoingMessages (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/backendAgent.js:490:25)
    at Bridge._flushWhileIdle (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/backendAgent.js:408:14)
    at _flushHandle.requestIdle.timeout (chrome-extension://oppikflppfjfdpjimpdadhelffjpciba/backendAgent.js:375:25)
```
![image](https://user-images.githubusercontent.com/18407013/48868666-a6422f00-ed97-11e8-80c2-d3c82d9ce39b.png)

Tested both the chrome store version and building it myself. Not sure what I'm missing. Here's a [potentially related stackoverflow discussion](https://stackoverflow.com/a/52223341)

If it helps, here's whats in `message`:
```
{
  "eventName": "Request",
  "seriesId": "cf60e6",
  "operation": {
    "kind": "Request",
    "operationKind": "query",
    "name": "TransactionStatusBarRefetchQuery",
    "id": null,
    "text": "query TransactionStatusBarRefetchQuery {\n  viewer {\n    ...TransactionStatusBar_viewer\n    id\n  }\n}\n\nfragment TransactionStatusBar_viewer on User {\n  id\n  buyerProfile {\n    id\n    privateKey {\n      id\n      pendingEthTransactions(first: 10) {\n        edges {\n          node {\n            id\n            hash\n            transaction {\n              hash\n              status\n            }\n          }\n        }\n      }\n    }\n  }\n}\n",
    "metadata": {
      
    },
    "fragment": {
      "kind": "Fragment",
      "name": "TransactionStatusBarRefetchQuery",
      "type": "Query",
      "metadata": null,
      "argumentDefinitions": [
        
      ],
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "name": "viewer",
          "storageKey": null,
          "args": null,
          "concreteType": "User",
          "plural": false,
          "selections": [
            {
              "kind": "FragmentSpread",
              "name": "TransactionStatusBar_viewer",
              "args": null
            }
          ]
        }
      ]
    },
    "operation": {
      "kind": "Operation",
      "name": "TransactionStatusBarRefetchQuery",
      "argumentDefinitions": [
        
      ],
      "selections": [
        {
          "kind": "LinkedField",
          "alias": null,
          "name": "viewer",
          "storageKey": null,
          "args": null,
          "concreteType": "User",
          "plural": false,
          "selections": [
            {
              "kind": "ScalarField",
              "alias": null,
              "name": "id",
              "args": null,
              "storageKey": null
            },
            {
              "kind": "LinkedField",
              "alias": null,
              "name": "buyerProfile",
              "storageKey": null,
              "args": null,
              "concreteType": "BuyerProfile",
              "plural": false,
              "selections": [
                {
                  "kind": "ScalarField",
                  "alias": null,
                  "name": "id",
                  "args": null,
                  "storageKey": null
                },
                {
                  "kind": "LinkedField",
                  "alias": null,
                  "name": "privateKey",
                  "storageKey": null,
                  "args": null,
                  "concreteType": "PrivateKey",
                  "plural": false,
                  "selections": [
                    {
                      "kind": "ScalarField",
                      "alias": null,
                      "name": "id",
                      "args": null,
                      "storageKey": null
                    },
                    {
                      "kind": "LinkedField",
                      "alias": null,
                      "name": "pendingEthTransactions",
                      "storageKey": "pendingEthTransactions(first:10)",
                      "args": [
                        {
                          "kind": "Literal",
                          "name": "first",
                          "value": 10,
                          "type": "Int"
                        }
                      ],
                      "concreteType": "PendingEthTransactionConnection",
                      "plural": false,
                      "selections": [
                        {
                          "kind": "LinkedField",
                          "alias": null,
                          "name": "edges",
                          "storageKey": null,
                          "args": null,
                          "concreteType": "PendingEthTransactionEdge",
                          "plural": true,
                          "selections": [
                            {
                              "kind": "LinkedField",
                              "alias": null,
                              "name": "node",
                              "storageKey": null,
                              "args": null,
                              "concreteType": "PendingEthTransaction",
                              "plural": false,
                              "selections": [
                                {
                                  "kind": "ScalarField",
                                  "alias": null,
                                  "name": "id",
                                  "args": null,
                                  "storageKey": null
                                },
                                {
                                  "kind": "ScalarField",
                                  "alias": null,
                                  "name": "hash",
                                  "args": null,
                                  "storageKey": null
                                },
                                {
                                  "kind": "LinkedField",
                                  "alias": null,
                                  "name": "transaction",
                                  "storageKey": null,
                                  "args": null,
                                  "concreteType": "EthQLTransaction",
                                  "plural": false,
                                  "selections": [
                                    {
                                      "kind": "ScalarField",
                                      "alias": null,
                                      "name": "hash",
                                      "args": null,
                                      "storageKey": null
                                    },
                                    {
                                      "kind": "ScalarField",
                                      "alias": null,
                                      "name": "status",
                                      "args": null,
                                      "storageKey": null
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    "hash": "25bd90fd8ff5276eb7c8dc20f4f755a3"
  },
  "variables": {
    
  },
  "environment": 0
}
```

**Comment by reckter** [comment]
This appears to be happening again, spamming full my console :/
